Repository overleaf/real-time, pull requests merged in 2020-06, with the labels that each got.

#143 update node to v10.21.0
  .nvmrc
  Dockerfile
  buildscript.txt
  docker-compose.yml
Labels: Team-Ops

#144 Merge master into v2
  .nvmrc
  Dockerfile
  Makefile
  buildscript.txt
  docker-compose.yml
Labels: Team-Ops

#148 [misc] socket.io: use a secondary publicId for public facing usages
  app/coffee/DocumentUpdaterController.coffee
  app/coffee/Router.coffee
  app/coffee/WebsocketController.coffee
  app/coffee/WebsocketLoadBalancer.coffee
  package.json
  test/acceptance/coffee/ApplyUpdateTests.coffee
  test/acceptance/coffee/ClientTrackingTests.coffee
  test/acceptance/coffee/JoinProjectTests.coffee
  test/acceptance/coffee/LeaveProjectTests.coffee
  test/acceptance/coffee/ReceiveUpdateTests.coffee
  test/acceptance/coffee/helpers/RealTimeClient.coffee
  test/unit/coffee/DocumentUpdaterControllerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
  test/unit/coffee/helpers/MockClient.coffee
Labels: Team-Ops

#149 [v2] socket.io: use a secondary publicId for public facing usages
  app/coffee/DocumentUpdaterController.coffee
  app/coffee/Router.coffee
  app/coffee/WebsocketController.coffee
  app/coffee/WebsocketLoadBalancer.coffee
  package.json
  test/acceptance/coffee/ApplyUpdateTests.coffee
  test/acceptance/coffee/ClientTrackingTests.coffee
  test/acceptance/coffee/JoinProjectTests.coffee
  test/acceptance/coffee/LeaveProjectTests.coffee
  test/acceptance/coffee/ReceiveUpdateTests.coffee
  test/acceptance/coffee/helpers/RealTimeClient.coffee
  test/unit/coffee/DocumentUpdaterControllerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
  test/unit/coffee/helpers/MockClient.coffee
Labels: Team-Ops

#146 [misc] downgrade logging when running tests
  test/acceptance/coffee/helpers/RealtimeServer.coffee
  test/unit/coffee/ChannelManagerTests.coffee
Labels: Team-Ops

#145 [backport] 140: stop processing requests as we detect a client disconnect
  app/coffee/RoomManager.coffee
  app/coffee/WebsocketController.coffee
  test/acceptance/coffee/EarlyDisconnect.coffee
  test/acceptance/coffee/LeaveDocTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#147 [backport] 141: Router: validate the callback argument
  app/coffee/Router.coffee
Labels: Team-Ops

#150 [misc] add test cases for the validation of the callback argument
  app/coffee/Router.coffee
  test/acceptance/coffee/RouterTests.coffee
Labels: Team-Magma, Team-Ops

#151 [perf] add a few short cuts to the packet decoding
  socket.io.patch.js
Labels: Team-Magma, Team-Ops

#152 [misc] vendor a patched session.socket.io middleware
  app.coffee
  app/coffee/SessionSockets.coffee
  package-lock.json
  package.json
  test/acceptance/coffee/SessionSocketsTests.coffee
  test/unit/coffee/SessionSocketsTests.coffee
Labels: Team-Magma, Team-Ops

#153 [backport] 108 and 112: DrainManager acceptance tests
  app/coffee/HttpApiController.coffee
  app/coffee/Router.coffee
  test/acceptance/coffee/DrainManagerTests.coffee
  test/acceptance/coffee/helpers/RealTimeClient.coffee
Labels: Team-Magma, Team-Ops

#154 [backport] 111 HttpController: 404 for missing clients and add tests
  app/coffee/HttpController.coffee
  test/acceptance/coffee/HttpControllerTests.coffee
Labels: Team-Magma, Team-Ops

#155 [backport] 107 and 116: Improve ReceiveUpdate acceptance tests
  test/acceptance/coffee/ApplyUpdateTests.coffee
  test/acceptance/coffee/ReceiveUpdateTests.coffee
Labels: Team-Magma, Team-Ops

#156 [misc] RoomManager: emitOnCompletion: properly handle Promise rejections
  app/coffee/RoomManager.coffee
  test/unit/coffee/RoomManagerTests.coffee
Labels: Team-Magma, type:bug

#160 [backport] 113 and 126: ol_context
  app/coffee/AuthorizationManager.coffee
  app/coffee/HttpController.coffee
  app/coffee/Router.coffee
  app/coffee/Utils.coffee
  app/coffee/WebsocketController.coffee
  app/coffee/WebsocketLoadBalancer.coffee
  test/unit/coffee/AuthorizationManagerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
  test/unit/coffee/WebsocketLoadBalancerTests.coffee
  test/unit/coffee/helpers/MockClient.coffee
Labels: Team-Magma
