Repository overleaf/real-time, pull requests merged in 2020-05, with the labels that each got.

#129 [misc] get the list of rooms a client is in in a synchronous fashion
  .editorconfig
  app/coffee/RoomManager.coffee
Labels: Team-Ops

#130 [misc] clear on subscribe failure
  .editorconfig
  app/coffee/ChannelManager.coffee
  package-lock.json
  package.json
  test/unit/coffee/AuthorizationManagerTests.coffee
  test/unit/coffee/ChannelManagerTests.coffee
  test/unit/coffee/WebApiManagerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops, type:bug

#131 [misc] restore the default pingTimeout of 60s from socket.io v0
  app.coffee
Labels: Team-Ops

#134 [WebsocketController] handle redis subscribe error on joinProject
  app/coffee/WebsocketController.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#135 [WebsocketController] skip leaveProject when joinProject didn't complete
  app/coffee/WebsocketController.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#136 [misc] backport sinon v2
  package-lock.json
  package.json
  test/unit/coffee/AuthorizationManagerTests.coffee
  test/unit/coffee/WebApiManagerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#137 [misc] backport strict sequence of redis (un)subscribe
  app/coffee/ChannelManager.coffee
  test/acceptance/coffee/LeaveProjectTests.coffee
  test/acceptance/coffee/PubSubRace.coffee
  test/unit/coffee/ChannelManagerTests.coffee
Labels: Team-Ops

#138 [misc] bump dependencies to latest patch versions
  package-lock.json
Labels: Team-Ops

#139 [misc] merge master into v2
  .editorconfig
  app/coffee/ChannelManager.coffee
  app/coffee/WebsocketController.coffee
  test/acceptance/coffee/PubSubRace.coffee
  test/unit/coffee/ChannelManagerTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#140 [misc] stop processing requests as we detect a client disconnect
  app/coffee/RoomManager.coffee
  app/coffee/WebsocketController.coffee
  test/acceptance/coffee/EarlyDisconnect.coffee
  test/acceptance/coffee/LeaveDocTests.coffee
  test/unit/coffee/WebsocketControllerTests.coffee
Labels: Team-Ops

#141 [Router] validate the callback argument
  app/coffee/Router.coffee
Labels: Team-Ops

#142 Add Fake Lint and Format Targets
  Makefile
Labels: Team-Magma
