Repository overleaf/real-time, pull requests merged in 2020-08, with the labels that each got.

#173 [misc] bump socket.io and socket.io-client: harden cleanup
  package-lock.json
  package.json
Labels: Team-Magma

#174 [misc] bump the dev-env to 3.3.0
  .github/dependabot.yml
  .npmrc
  Dockerfile
  Jenkinsfile
  Makefile
  buildscript.txt
  docker-compose.ci.yml
  docker-compose.yml
  nodemon.json
  package.json
Labels: Team-Magma

#175 [misc] bump the dev-env to 3.3.1
  .gitignore
  .npmrc
  buildscript.txt
Labels: Team-Magma, type:bug

#177 clean up join/leave handling
  app/js/DocumentUpdaterManager.js
  app/js/Router.js
  app/js/WebsocketController.js
  test/unit/js/WebsocketControllerTests.js
  test/unit/js/helpers/MockClient.js
Labels: Team-Magma

#176 [misc] bump the dev-env to 3.3.2
  buildscript.txt
Labels: Team-Magma

#178 [app] ignore errors from accessing disconnected client sockets
  app.js
Labels: Team-Magma

#179 [misc] bump logger-sharelatex to version 2.2.0
  package-lock.json
  package.json
Labels: Team-Ops

#180 [misc] bump socket.io and socket.io-client
  package-lock.json
  package.json
Labels: Team-Magma

#181 [misc] forcefully disconnect from shutdown process
  app.js
  app/js/DrainManager.js
  config/settings.defaults.js
Labels: Team-Magma

#183 [misc] increase the timeout for unit tests -- CI boxes are too slow
  package.json
Labels: Team-Magma

#184 [misc] migrate to custom OErrors
  app/js/AuthorizationManager.js
  app/js/DocumentUpdaterManager.js
  app/js/Errors.js
  app/js/Router.js
  app/js/SafeJsonParse.js
  app/js/SessionSockets.js
  app/js/WebApiManager.js
  app/js/WebsocketController.js
  package.json
  test/unit/js/DocumentUpdaterManagerTests.js
  test/unit/js/SafeJsonParseTest.js
  test/unit/js/WebApiManagerTests.js
  test/unit/js/WebsocketControllerTests.js
Labels: Team-Magma

#185 [misc] add/bring back doc_id in error context
  app/js/Router.js
Labels: Team-Magma

#186 [misc] fix join project error context
  app/js/Router.js
Labels: Team-Magma

#187 [misc] migrate to OError tagging/wrapping
  app/js/ChannelManager.js
  app/js/ConnectedUsersManager.js
  app/js/DocumentUpdaterManager.js
  app/js/RoomManager.js
  app/js/SessionSockets.js
  app/js/WebApiManager.js
  app/js/WebsocketController.js
  test/unit/js/ChannelManagerTests.js
  test/unit/js/WebsocketControllerTests.js
Labels: Team-Magma
